//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class csejustEntities : DbContext
    {
        public csejustEntities()
            : base("name=csejustEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<book> books { get; set; }
        public virtual DbSet<material> materials { get; set; }
        public virtual DbSet<notice> notices { get; set; }
        public virtual DbSet<result> results { get; set; }
        public virtual DbSet<routine> routines { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<teacher> teachers { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<usertype> usertypes { get; set; }
        public virtual DbSet<activity> activities { get; set; }
        public virtual DbSet<carrier_t> carrier_t { get; set; }
        public virtual DbSet<current_academic> current_academic { get; set; }
        public virtual DbSet<previous_academic> previous_academic { get; set; }
    }
}
