//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class notice
    {
        public int notice_id { get; set; }
        public string notice_topic { get; set; }
        public string published_by { get; set; }
        public System.DateTime publish_date { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_date { get; set; }
        public string updated_by { get; set; }
        public System.DateTime updated_date { get; set; }
        public string deadline { get; set; }
        public string priority { get; set; }
        public string specification { get; set; }
    }
}
