//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class previous_academic
    {
        public int user_id { get; set; }
        public int student_id { get; set; }
        public int hsc_roll { get; set; }
        public int hsc_reg { get; set; }
        public double hsc_result { get; set; }
        public string hsc_board { get; set; }
        public string hsc_college { get; set; }
        public string hsc_section { get; set; }
        public int ssc_roll { get; set; }
        public int ssc_reg { get; set; }
        public double ssc_result { get; set; }
        public string ssc_board { get; set; }
        public string ssc_school { get; set; }
        public string ssc_section { get; set; }
    
        public virtual student student { get; set; }
        public virtual user user { get; set; }
    }
}
