//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class routine
    {
        public int routine_id { get; set; }
        public System.DateTime class_date { get; set; }
        public string day { get; set; }
        public int teacher_id { get; set; }
        public string subject_name { get; set; }
        public string subject_code { get; set; }
        public string session { get; set; }
        public System.TimeSpan start_time { get; set; }
        public System.TimeSpan end_time { get; set; }
        public string duration { get; set; }
        public string comment { get; set; }
    
        public virtual teacher teacher { get; set; }
    }
}
