//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public teacher()
        {
            this.routines = new HashSet<routine>();
            this.carrier_t = new HashSet<carrier_t>();
        }
    
        public int teacher_id { get; set; }
        public int user_id { get; set; }
        public int usertype_id { get; set; }
        public string designation { get; set; }
        public string favorite_quote { get; set; }
        public string work_area { get; set; }
        public string achievement { get; set; }
        public string publication { get; set; }
        public string publication_links { get; set; }
        public string website { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<routine> routines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<carrier_t> carrier_t { get; set; }
        public virtual user user { get; set; }
        public virtual usertype usertype { get; set; }
    }
}
